# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'praktikum10.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(670, 400)
        Form.setMinimumSize(QtCore.QSize(670, 400))
        Form.setMaximumSize(QtCore.QSize(670, 400))
        Form.setStyleSheet("/* ============================== */\n"
"/* BACKGROUND FORM (Putih bersih) */\n"
"QWidget {\n"
"    background-color: white;\n"
"}\n"
"\n"
"/* ============================== */\n"
"/* DEFAULT STYLE UNTUK SEMUA QPushButton */\n"
"QPushButton {\n"
"    font-weight: bold;\n"
"    border: 1px solid #1a5fb4;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    background-color: #ffffff;\n"
"    color: #1a5fb4;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e6f0ff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #cce0ff;\n"
"}\n"
"\n"
"/* ============================== */\n"
"/* TOMBOL KHUSUS RGB (DIATUR BERDASARKAN objectName) */\n"
"\n"
"/* Red */\n"
"QPushButton#btn_hr {\n"
"    background-color: #E53935;\n"
"    color: white;\n"
"}\n"
"QPushButton#btn_hr:hover {\n"
"    background-color: #D32F2F;\n"
"}\n"
"QPushButton#btn_hr:pressed {\n"
"    background-color: #B71C1C;\n"
"}\n"
"\n"
"/* Green */\n"
"QPushButton#btn_hg {\n"
"    background-color: #43A047;\n"
"    color: white;\n"
"}\n"
"QPushButton#btn_hg:hover {\n"
"    background-color: #388E3C;\n"
"}\n"
"QPushButton#btn_hg:pressed {\n"
"    background-color: #1B5E20;\n"
"}\n"
"\n"
"/* Blue */\n"
"QPushButton#btn_hb {\n"
"    background-color: #1E88E5;\n"
"    color: white;\n"
"}\n"
"QPushButton#btn_hb:hover {\n"
"    background-color: #1976D2;\n"
"}\n"
"QPushButton#btn_hb:pressed {\n"
"    background-color: #0D47A1;\n"
"}\n"
"\n"
"/* ============================== */\n"
"/* QLabel untuk Preview Gambar */\n"
"QLabel#label_preview {\n"
"    border: 1px solid #999999;\n"
"    background-color: #fdfdfd;\n"
"}\n"
"\n"
"/* ============================== */\n"
"/* QFrame untuk Plot Histogram */\n"
"QFrame {\n"
"    border: 1px solid #cccccc;\n"
"    background-color: #f8f8f8;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.label_preview = QtWidgets.QLabel(Form)
        self.label_preview.setGeometry(QtCore.QRect(30, 10, 180, 120))
        self.label_preview.setMinimumSize(QtCore.QSize(0, 0))
        self.label_preview.setMaximumSize(QtCore.QSize(180, 120))
        self.label_preview.setFrameShape(QtWidgets.QFrame.Box)
        self.label_preview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_preview.setObjectName("label_preview")
        self.btn_load = QtWidgets.QPushButton(Form)
        self.btn_load.setGeometry(QtCore.QRect(70, 150, 100, 30))
        self.btn_load.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_load.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_load.setObjectName("btn_load")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(230, 270, 409, 122))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_hb = QtWidgets.QPushButton(self.widget)
        self.btn_hb.setMinimumSize(QtCore.QSize(40, 25))
        self.btn_hb.setMaximumSize(QtCore.QSize(40, 25))
        self.btn_hb.setObjectName("btn_hb")
        self.horizontalLayout_3.addWidget(self.btn_hb)
        self.frame_b = QtWidgets.QFrame(self.widget)
        self.frame_b.setMinimumSize(QtCore.QSize(360, 120))
        self.frame_b.setMaximumSize(QtCore.QSize(360, 120))
        self.frame_b.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_b.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_b.setObjectName("frame_b")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_b)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3.addWidget(self.frame_b)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(230, 140, 409, 122))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_hg = QtWidgets.QPushButton(self.widget1)
        self.btn_hg.setMinimumSize(QtCore.QSize(40, 25))
        self.btn_hg.setMaximumSize(QtCore.QSize(40, 25))
        self.btn_hg.setObjectName("btn_hg")
        self.horizontalLayout_2.addWidget(self.btn_hg)
        self.frame_g = QtWidgets.QFrame(self.widget1)
        self.frame_g.setMinimumSize(QtCore.QSize(360, 120))
        self.frame_g.setMaximumSize(QtCore.QSize(360, 120))
        self.frame_g.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_g.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_g.setObjectName("frame_g")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_g)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2.addWidget(self.frame_g)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(230, 10, 409, 122))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_hr = QtWidgets.QPushButton(self.widget2)
        self.btn_hr.setMinimumSize(QtCore.QSize(40, 25))
        self.btn_hr.setMaximumSize(QtCore.QSize(40, 25))
        self.btn_hr.setObjectName("btn_hr")
        self.horizontalLayout.addWidget(self.btn_hr)
        self.frame_r = QtWidgets.QFrame(self.widget2)
        self.frame_r.setMinimumSize(QtCore.QSize(360, 120))
        self.frame_r.setMaximumSize(QtCore.QSize(360, 120))
        self.frame_r.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_r.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_r.setObjectName("frame_r")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_r)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addWidget(self.frame_r)
        self.btn_toggle_mode = QtWidgets.QPushButton(Form)
        self.btn_toggle_mode.setGeometry(QtCore.QRect(70, 190, 100, 30))
        self.btn_toggle_mode.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_toggle_mode.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_toggle_mode.setObjectName("btn_toggle_mode")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Praktikum 10"))
        self.label_preview.setText(_translate("Form", "Gambar"))
        self.btn_load.setText(_translate("Form", "Load Gambar"))
        self.btn_hb.setText(_translate("Form", "HB"))
        self.btn_hg.setText(_translate("Form", "HG"))
        self.btn_hr.setText(_translate("Form", "HR"))
        self.btn_toggle_mode.setText(_translate("Form", "Fundamental"))
